import { describe, it, expect, vi, beforeEach } from 'vitest';
import { exportToPDF, generatePDFReport, exportToCSV } from './exportUtils';

/**
 * US-091 upgraded jspdf 2.x -> 4.x and jspdf-autotable 3.x -> 5.x — both major
 * bumps, taken to clear a critical advisory (path traversal, PDF/JS injection,
 * several DoS). A typecheck does not exercise a rendering library, so these
 * drive the real code paths and assert they run to the download step.
 */
describe('PDF export (jspdf v4 + jspdf-autotable v5)', () => {
  let clicks: number;

  beforeEach(() => {
    clicks = 0;
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {
      clicks += 1;
    });
    globalThis.URL.createObjectURL = vi.fn(
      () => 'blob:mock'
    ) as unknown as typeof URL.createObjectURL;
    globalThis.URL.revokeObjectURL = vi.fn();
  });

  const headers = ['Name', 'Email', 'Status'];
  const rows = [
    ['Alice', 'alice@example.com', 'new'],
    ['Bob', 'bob@example.com', 'contacted'],
  ];

  it('renders a table to PDF without throwing', () => {
    expect(() => exportToPDF({ title: 'Lead Report', headers, rows })).not.toThrow();
  });

  it('renders a full report — summary cards, autotable, footer', () => {
    expect(() =>
      generatePDFReport({
        title: 'Performance',
        subtitle: 'Last 30 days',
        dateRange: 'Jul 9 - Aug 8',
        headers,
        rows,
        summary: [
          { label: 'Views', value: '1,204' },
          { label: 'Leads', value: 38 },
        ],
        footer: 'Generated by AgentBio',
        orientation: 'landscape',
        theme: 'grid',
      })
    ).not.toThrow();
  });

  it('exports CSV and triggers a download', () => {
    exportToCSV({ title: 'Leads', headers, rows });
    expect(clicks).toBeGreaterThan(0);
  });

  /**
   * US-104: the Leads page hand-rolled its own CSV beside this one, quoting
   * only `message`. A lead named "Smith, John" therefore split into two
   * columns in Excel and shifted every field after it. The page uses this
   * function now, so the escaping is worth asserting rather than assuming.
   */
  describe('CSV escaping', () => {
    // jsdom's Blob has no .text(), so the parts are captured at construction.
    const csvFrom = (data: Parameters<typeof exportToCSV>[0]): string => {
      let captured = '';
      const RealBlob = globalThis.Blob;
      class CapturingBlob extends RealBlob {
        constructor(parts: BlobPart[], options?: BlobPropertyBag) {
          super(parts, options);
          captured = parts.map(String).join('');
        }
      }
      globalThis.Blob = CapturingBlob as unknown as typeof Blob;
      try {
        exportToCSV(data);
      } finally {
        globalThis.Blob = RealBlob;
      }
      return captured;
    };

    it('quotes a value containing a comma, so it stays one column', () => {
      const csv = csvFrom({
        title: 'Leads',
        headers: ['Name', 'Status'],
        rows: [['Smith, John', 'new']],
      });
      expect(csv).toContain('"Smith, John",new');
    });

    it('doubles embedded quotes rather than terminating the field', () => {
      const csv = csvFrom({
        title: 'Leads',
        headers: ['Name', 'Note'],
        rows: [['Ada', 'She said \"call me back\"']],
      });
      expect(csv).toContain('"She said \"\"call me back\"\""');
    });

    it('quotes a value containing a newline', () => {
      const csv = csvFrom({
        title: 'Leads',
        headers: ['Name', 'Message'],
        rows: [['Ada', 'line one\nline two']],
      });
      expect(csv).toContain('"line one\nline two"');
    });

    it('leaves an ordinary value unquoted', () => {
      const csv = csvFrom({
        title: 'Leads',
        headers: ['Name', 'Status'],
        rows: [['Ada', 'new']],
      });
      expect(csv).toContain('Ada,new');
    });
  });
});
