/**
 * Social Share Component
 * Enables viral sharing of listing descriptions with pre-populated posts
 */

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Share2, Download, Facebook, Linkedin, Twitter, Copy, Check } from 'lucide-react';
import { toast } from 'sonner';

interface SocialShareProps {
  propertyAddress: string;
  city: string;
  state: string;
  price: number;
  propertyType: string;
  description: string;
}

export function SocialShare({
  propertyAddress,
  city,
  state,
  price,
  propertyType,
  description,
}: SocialShareProps) {
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);

  // Generate pre-populated social posts
  const shareTexts = {
    facebook: `🏠 NEW LISTING ALERT!\n\n${propertyAddress}\n${city}, ${state}\n💰 $${price.toLocaleString()}\n\n${description.substring(0, 200)}...\n\nDM me for details or schedule a showing! 🔑`,

    linkedin: `🏡 Excited to share this exceptional ${propertyType} in ${city}!\n\n📍 ${propertyAddress}\n💵 Listed at $${price.toLocaleString()}\n\n${description.substring(0, 150)}...\n\nReach out if you or someone you know is looking in this area. Let's connect! #RealEstate #${city.replace(/\s+/g, '')}`,

    twitter: `🏠 Just listed in ${city}! $${price.toLocaleString()}\n\n${description.substring(0, 120)}...\n\nDM for details! #RealEstate #${city.replace(/\s+/g, '')} #NewListing`,

    instagram: `🏠 NEW LISTING 🔑\n\n${city}, ${state}\n💰 $${price.toLocaleString()}\n\n${description.substring(0, 100)}...\n\nDM me for details!\n\n#realestate #${city.toLowerCase().replace(/\s+/g, '')}realestate #newhome #dreamhome #househunting #realtor #listingalert`,

    email: `Subject: New Listing Alert - ${propertyAddress}\n\nHi [Name],\n\nI wanted to reach out about an incredible property that just hit the market in ${city}:\n\n${propertyAddress}\n${city}, ${state}\n$${price.toLocaleString()}\n\n${description}\n\nWould you like to schedule a showing? I have availability this week.\n\nBest regards,\n[Your Name]`,
  };

  // Copy description to clipboard
  const handleCopyDescription = async () => {
    try {
      await navigator.clipboard.writeText(description);
      setCopied(true);
      toast.success('Description copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast.error('Failed to copy description');
    }
  };

  // Share to social media
  const handleShare = (platform: 'facebook' | 'linkedin' | 'twitter') => {
    const urls: Record<string, string> = {
      facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(window.location.href)}&quote=${encodeURIComponent(shareTexts.facebook)}`,
      linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(window.location.href)}`,
      twitter: `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareTexts.twitter)}`,
    };

    window.open(urls[platform], '_blank', 'width=600,height=400');

    // Track analytics
    trackShare(platform);
  };

  // Copy pre-populated post
  const handleCopyPost = async (platform: keyof typeof shareTexts) => {
    try {
      await navigator.clipboard.writeText(shareTexts[platform]);
      toast.success(`${platform.charAt(0).toUpperCase() + platform.slice(1)} post copied!`);
      trackShare(`copy-${platform}`);
    } catch (error) {
      toast.error('Failed to copy post');
    }
  };

  // Download as text file
  const handleDownloadDescription = () => {
    setDownloading(true);

    const content = `${propertyAddress}\n${city}, ${state}\n$${price.toLocaleString()}\n\n${description}\n\n---\nGenerated by AgentBio.net Listing Description Generator\nCreate your own: https://agentbio.net/tools/listing-description-generator`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${city.replace(/\s+/g, '-')}-listing-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);

    setTimeout(() => setDownloading(false), 1000);
    toast.success('Description downloaded!');
    trackShare('download');
  };

  // Track sharing analytics
  const trackShare = (platform: string) => {
    // This will be wired up to Supabase analytics
    console.log('Share tracked:', platform);
  };

  return (
    <div className="space-y-6">
      {/* Quick Actions */}
      <Card className="p-6">
        <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
          <Share2 className="h-5 w-5 text-purple-600" />
          Share This Listing
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {/* Copy Description */}
          <Button
            onClick={handleCopyDescription}
            variant="outline"
            className="justify-start gap-2"
          >
            {copied ? <Check className="h-4 w-4 text-green-600" /> : <Copy className="h-4 w-4" />}
            {copied ? 'Copied!' : 'Copy Full Description'}
          </Button>

          {/* Download */}
          <Button
            onClick={handleDownloadDescription}
            variant="outline"
            className="justify-start gap-2"
            disabled={downloading}
          >
            <Download className="h-4 w-4" />
            {downloading ? 'Downloading...' : 'Download as TXT'}
          </Button>

          {/* Social Shares */}
          <Button
            onClick={() => handleShare('facebook')}
            variant="outline"
            className="justify-start gap-2 text-blue-600 hover:text-blue-700"
          >
            <Facebook className="h-4 w-4" />
            Share on Facebook
          </Button>

          <Button
            onClick={() => handleShare('linkedin')}
            variant="outline"
            className="justify-start gap-2 text-blue-700 hover:text-blue-800"
          >
            <Linkedin className="h-4 w-4" />
            Share on LinkedIn
          </Button>

          <Button
            onClick={() => handleShare('twitter')}
            variant="outline"
            className="justify-start gap-2 text-sky-500 hover:text-sky-600"
          >
            <Twitter className="h-4 w-4" />
            Share on Twitter
          </Button>
        </div>
      </Card>

      {/* Pre-populated Posts */}
      <Card className="p-6">
        <h3 className="text-lg font-semibold mb-4">Pre-Written Social Posts</h3>
        <p className="text-sm text-gray-600 mb-4">
          Click to copy these ready-to-use posts for each platform:
        </p>

        <div className="space-y-4">
          {/* Facebook */}
          <div className="border rounded-lg p-4 bg-gray-50">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2 font-medium">
                <Facebook className="h-4 w-4 text-blue-600" />
                Facebook
              </div>
              <Button
                size="sm"
                variant="ghost"
                onClick={() => handleCopyPost('facebook')}
              >
                <Copy className="h-3 w-3 mr-1" />
                Copy
              </Button>
            </div>
            <p className="text-sm text-gray-700 whitespace-pre-line">
              {shareTexts.facebook}
            </p>
          </div>

          {/* Instagram */}
          <div className="border rounded-lg p-4 bg-gray-50">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2 font-medium">
                <svg className="h-4 w-4" viewBox="0 0 24 24" fill="url(#instagram-gradient)">
                  <defs>
                    <linearGradient id="instagram-gradient" x1="0%" y1="0%" x2="100%" y2="100%">
                      <stop offset="0%" stopColor="#f09433" />
                      <stop offset="25%" stopColor="#e6683c" />
                      <stop offset="50%" stopColor="#dc2743" />
                      <stop offset="75%" stopColor="#cc2366" />
                      <stop offset="100%" stopColor="#bc1888" />
                    </linearGradient>
                  </defs>
                  <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/>
                </svg>
                Instagram
              </div>
              <Button
                size="sm"
                variant="ghost"
                onClick={() => handleCopyPost('instagram')}
              >
                <Copy className="h-3 w-3 mr-1" />
                Copy
              </Button>
            </div>
            <p className="text-sm text-gray-700 whitespace-pre-line">
              {shareTexts.instagram}
            </p>
          </div>

          {/* LinkedIn */}
          <div className="border rounded-lg p-4 bg-gray-50">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2 font-medium">
                <Linkedin className="h-4 w-4 text-blue-700" />
                LinkedIn
              </div>
              <Button
                size="sm"
                variant="ghost"
                onClick={() => handleCopyPost('linkedin')}
              >
                <Copy className="h-3 w-3 mr-1" />
                Copy
              </Button>
            </div>
            <p className="text-sm text-gray-700 whitespace-pre-line">
              {shareTexts.linkedin}
            </p>
          </div>

          {/* Email */}
          <div className="border rounded-lg p-4 bg-gray-50">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2 font-medium">
                <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                </svg>
                Email Template
              </div>
              <Button
                size="sm"
                variant="ghost"
                onClick={() => handleCopyPost('email')}
              >
                <Copy className="h-3 w-3 mr-1" />
                Copy
              </Button>
            </div>
            <p className="text-sm text-gray-700 whitespace-pre-line font-mono text-xs">
              {shareTexts.email}
            </p>
          </div>
        </div>
      </Card>

      {/* Viral Referral CTA */}
      <Card className="p-6 bg-gradient-to-br from-purple-50 to-pink-50 border-purple-200">
        <h3 className="text-lg font-semibold mb-2">Love this tool? Share it!</h3>
        <p className="text-sm text-gray-700 mb-4">
          Share the AI Listing Description Generator with 3 colleagues and get our <strong>Premium Real Estate Photography Checklist</strong> (worth $97) for free!
        </p>
        <Button
          onClick={() => handleCopyPost('email')}
          className="w-full bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700"
        >
          Share with Colleagues
        </Button>
      </Card>
    </div>
  );
}
