-- ============================================================================
-- Add three tables the application already queries but no migration ever created
-- ============================================================================
-- Found by diffing every `.from('<table>')` in src/ and supabase/functions/
-- against the tables that supabase/migrations/ actually creates. These three
-- had no definition anywhere, so the features that depend on them fail at
-- runtime. Each failure is swallowed by a try/catch or an ignored error, so the
-- features look present in the UI but silently do nothing:
--
--   lead_notes             -- LeadDetailModal: the notes timeline never loads,
--                             and the automatic "Status changed to: X" audit
--                             note is never written. This modal IS reachable,
--                             so the feature is visibly broken today.
--   invoices               -- SubscriptionPage billing history is always empty;
--                             stripe-webhook's invoice.paid handler logs
--                             "Could not record invoice" and drops the row.
--                             Also reachable today.
--   mortgage_calculations  -- MortgageCalculator writes here. That component is
--                             currently unreachable (nothing imports it, and it
--                             imports a @/components/ui/slider that does not
--                             exist), so this table is created ahead of the
--                             component being wired up rather than to fix a
--                             live failure. Included because the call sites
--                             already exist and pin the column names.
--
-- Column names below are taken from the existing call sites so that no
-- application code has to change.

-- ----------------------------------------------------------------------------
-- lead_notes
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lead_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id UUID NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  note TEXT NOT NULL,
  -- System notes are generated by the app (e.g. status transitions) rather than
  -- typed by the agent; the UI renders them differently.
  is_system BOOLEAN NOT NULL DEFAULT false,
  -- Audit only. LeadDetailModal does not send this, so it must be defaultable.
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.lead_notes IS
  'Free-text and system-generated notes attached to a lead, newest first in the UI.';

-- LeadDetailModal always filters by lead_id and orders by created_at DESC.
CREATE INDEX IF NOT EXISTS idx_lead_notes_lead_id_created_at
  ON public.lead_notes(lead_id, created_at DESC);

ALTER TABLE public.lead_notes ENABLE ROW LEVEL SECURITY;

-- Notes have no user_id of their own: ownership is inherited from the parent
-- lead, so every policy checks that the caller owns the lead.
DROP POLICY IF EXISTS "Users can read notes on their own leads" ON public.lead_notes;
CREATE POLICY "Users can read notes on their own leads"
  ON public.lead_notes FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.leads l
    WHERE l.id = lead_notes.lead_id AND l.user_id = auth.uid()
  ));

DROP POLICY IF EXISTS "Users can add notes to their own leads" ON public.lead_notes;
CREATE POLICY "Users can add notes to their own leads"
  ON public.lead_notes FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.leads l
    WHERE l.id = lead_notes.lead_id AND l.user_id = auth.uid()
  ));

DROP POLICY IF EXISTS "Users can update notes on their own leads" ON public.lead_notes;
CREATE POLICY "Users can update notes on their own leads"
  ON public.lead_notes FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM public.leads l
    WHERE l.id = lead_notes.lead_id AND l.user_id = auth.uid()
  ));

DROP POLICY IF EXISTS "Users can delete notes on their own leads" ON public.lead_notes;
CREATE POLICY "Users can delete notes on their own leads"
  ON public.lead_notes FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM public.leads l
    WHERE l.id = lead_notes.lead_id AND l.user_id = auth.uid()
  ));

-- ----------------------------------------------------------------------------
-- mortgage_calculations
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mortgage_calculations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- The agent whose public profile hosted the calculator.
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  listing_id UUID REFERENCES public.listings(id) ON DELETE SET NULL,

  -- Inputs.
  home_price NUMERIC(14, 2) NOT NULL,
  down_payment NUMERIC(14, 2),
  down_payment_percent NUMERIC(6, 3),
  interest_rate NUMERIC(6, 3),
  loan_term_years INTEGER,
  property_tax_annual NUMERIC(14, 2),
  home_insurance_annual NUMERIC(14, 2),
  hoa_monthly NUMERIC(14, 2),
  pmi_monthly NUMERIC(14, 2),

  -- Computed results, stored so the funnel can be analysed without recomputing.
  loan_amount NUMERIC(14, 2),
  monthly_payment NUMERIC(14, 2),
  monthly_payment_breakdown JSONB NOT NULL DEFAULT '{}'::jsonb,
  total_interest NUMERIC(14, 2),
  total_cost NUMERIC(14, 2),

  -- Filled in only if the visitor converts into a lead.
  visitor_name TEXT,
  visitor_email TEXT,
  visitor_phone TEXT,
  lead_id UUID REFERENCES public.leads(id) ON DELETE SET NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.mortgage_calculations IS
  'One row per mortgage calculator run on a public profile. Anonymous visitors '
  'may insert; only the owning agent may read.';

CREATE INDEX IF NOT EXISTS idx_mortgage_calculations_user_id_created_at
  ON public.mortgage_calculations(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mortgage_calculations_lead_id
  ON public.mortgage_calculations(lead_id) WHERE lead_id IS NOT NULL;

ALTER TABLE public.mortgage_calculations ENABLE ROW LEVEL SECURITY;

-- The calculator lives on a public profile page, so the insert is unauthenticated.
-- This mirrors how public lead capture is already handled elsewhere: anyone may
-- write a row, nobody anonymous may read one back.
DROP POLICY IF EXISTS "Anyone can record a mortgage calculation" ON public.mortgage_calculations;
CREATE POLICY "Anyone can record a mortgage calculation"
  ON public.mortgage_calculations FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Agents can read their own mortgage calculations" ON public.mortgage_calculations;
CREATE POLICY "Agents can read their own mortgage calculations"
  ON public.mortgage_calculations FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Agents can update their own mortgage calculations" ON public.mortgage_calculations;
CREATE POLICY "Agents can update their own mortgage calculations"
  ON public.mortgage_calculations FOR UPDATE
  USING (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- invoices
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.invoices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Derived from stripe_subscription_id by the trigger below: the webhook that
  -- writes this table does not know the AgentBio user id, but RLS needs it.
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  -- stripe-webhook upserts on this column, so it must be unique.
  stripe_invoice_id TEXT NOT NULL UNIQUE,
  stripe_subscription_id TEXT,
  amount NUMERIC(12, 2) NOT NULL,
  currency TEXT DEFAULT 'usd',
  status TEXT NOT NULL,
  paid_at TIMESTAMPTZ,
  invoice_pdf TEXT,
  hosted_invoice_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.invoices IS
  'Stripe invoice history, written by the stripe-webhook function and shown as '
  'billing history on the subscription page.';

CREATE INDEX IF NOT EXISTS idx_invoices_user_id_paid_at
  ON public.invoices(user_id, paid_at DESC);

-- SubscriptionPage orders by paid_at without filtering on user_id, relying on
-- RLS to scope the result, so user_id must always be populated.
CREATE OR REPLACE FUNCTION public.set_invoice_user_id()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.user_id IS NULL AND NEW.stripe_subscription_id IS NOT NULL THEN
    SELECT us.user_id INTO NEW.user_id
    FROM public.user_subscriptions us
    WHERE us.stripe_subscription_id = NEW.stripe_subscription_id
    LIMIT 1;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_set_invoice_user_id ON public.invoices;
CREATE TRIGGER trg_set_invoice_user_id
  BEFORE INSERT OR UPDATE ON public.invoices
  FOR EACH ROW EXECUTE FUNCTION public.set_invoice_user_id();

ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

-- Read-only for users. Writes come from stripe-webhook using the service role
-- key, which bypasses RLS, so no INSERT/UPDATE policy is granted here.
DROP POLICY IF EXISTS "Users can read their own invoices" ON public.invoices;
CREATE POLICY "Users can read their own invoices"
  ON public.invoices FOR SELECT
  USING (auth.uid() = user_id);
